{% set version = "1.1.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bench
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bench_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bench/bench_{{ version }}.tar.gz
  sha256: bfae6320ad8c0c84fa6832519fac0e783e8d3ac5e3019ff6526f8060e8f1f317

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-glue
    - r-pillar
    - r-profmem
    - r-rlang >=0.2.0
    - r-tibble >=3.0.1
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-glue
    - r-pillar
    - r-profmem
    - r-rlang >=0.2.0
    - r-tibble >=3.0.1

test:
  commands:
    - $R -e "library('bench')"           # [not win]
    - "\"%R%\" -e \"library('bench')\""  # [win]

about:
  home: https://github.com/r-lib/bench
  license: MIT
  summary: Tools to accurately benchmark and analyze execution times for R expressions.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor
