appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: kw7y22E36d1iXpLyaWXfin74jJY5rGwXiRXClXphyYFG0dNv9/zSbKowurJBBFLT8AMQUF8+886wWGf/djLrS/AqsRALn85SnUQpvNPpuOJtozXhHJIdxfuh1tSUX4l/i+MFLvbYsRaHhDxjgERj7H+bCUO+UBA+lgD8LabtH6xVQ+uqsvesrr6X/VrNWACqa9tJ8cUvGamJexy3rYPdD/FVGmDMqhLnAvhnTuMfGd31RENeBBtC62kmlk3FmC5wPTuxl0IELBI9bb/ddareMuukWocwxbeiXCGhIdsIelwQ9LiRZ/fFQW5yQnT6kwExMriuM7LivacJiHdAjx4DFAro9HxTxtnxgxurM8BhLDdUz0C8lwZNWqmtDHtqWBiDAwP1zxFNmWTcqkXhfiW9Fsvyjv5WuKshON8ZZoSnOwv47x+oR/VaVCDuH0+rpjwj3ewTsw0mNCUtFPbv9DIpXIGxyPSuZQt5MSSkEcde86P/o2M+01PvakFm5o7pP4mHnvjHInnEstsGlLcaXsDj69BX0GWPO0we7pM61O3+vovRUcDN8sfDbtyU7Go0Z6m5ZTiilgOiXYR2E41y/knNzXUj8Pm/Iz54QHlpKlTLB5gLV5wYtbLZMbtQ+hbAnUraPX0BiRZU6YTnBFA8AxAH3CqoWpCf8b83BCdbVtiUqQ8=}
bot:
  automerge: true
